### ISSUE TITLE
Failed to get `elrond-wasm`

### ISSUE THREAD

**Issue by butavpaul** [ElrondNetwork/elrond-wasm-rs#540]
Hi! I'm new and I'm playing with the examples.

I've downloaded nft-minter and following this steps https://www.youtube.com/watch?v=IdkgvlK3rb8&list=PLQVcheGWwBRUTaG59ZybxJsPhMKS1pkHM&index=2 when I run erdpy contract build it throws this error.

```
error: failed to get `elrond-wasm` as a dependency of package `nft-minter-meta v0.0.0 (/home/zozel/dApp/NFTMinter/meta)`

Caused by:
failed to load source for dependency `elrond-wasm`

Caused by:
Unable to update /home/elrond-wasm

Caused by:
failed to read `/home/elrond-wasm/Cargo.toml`
```
With ping-pong example the contract is build and deployed without any problems.

**Comment by Dev4Elrond** [comment]
I had the same issue in the IDE. It worked when I used the command line.

**Comment by dorin-iancu** [comment]
There was a bug in the templates having local paths, I believe this was fixed.

**Comment by bh717** [comment]
@butavpaul , I am still getting your error. How did you fix this before?
I'd really appreciate it if you give me any advise. Thanks
